# -*- coding: utf-8 -*-
"""crf_ner.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PS-KAreakMJDZC1LYkBr4WUXTNopWotR
"""

!pip install datasets

from datasets import load_dataset
import pandas as pd

raw_datasets = load_dataset("xtreme", name="PAN-X.tr")

print("Türkçe NER veri seti (PAN-X.tr) indirildi ve yüklendi.")
print(raw_datasets)

ner_feature = raw_datasets['train'].features['ner_tags']
label_list = ner_feature.feature.names

def align_data_for_crf(dataset):
    processed_data = []
    for example in dataset:
        sentence = []

        tokens = example['tokens']
        tags_id = example['ner_tags']

        for token, tag_id in zip(tokens, tags_id):

            tag_name = label_list[tag_id]
            sentence.append((token, tag_name))
        processed_data.append(sentence)
    return processed_data


train_data = align_data_for_crf(raw_datasets['train'])
test_data = align_data_for_crf(raw_datasets['test'])

print("-" * 50)
print(f"Eğitim Cümle Sayısı: {len(train_data)}")
print(f"İlk Cümle Örneği (Kelime, Etiket): {train_data[0]}")

import sklearn_crfsuite
from sklearn.model_selection import train_test_split

def word2features(sent, i):
    """Defines the feature set for a single word (token)."""
    word = sent[i][0]


    features = {
        'bias': 1.0,
        'word.lower()': word.lower(),
        'word[-3:]': word[-3:],
        'word[-2:]': word[-2:],
        'word.isupper()': word.isupper(),
        'word.istitle()': word.istitle(),
        'word.isdigit()': word.isdigit(),
    }


    if i > 0:
        word1 = sent[i-1][0]
        tag1 = sent[i-1][1]
        features.update({
            '-1:word.lower()': word1.lower(),
            '-1:word.istitle()': word1.istitle(),
            '-1:word.isupper()': word1.isupper(),
            '-1:tag': tag1
        })
    else:
        features['BOS'] = True


    if i < len(sent) - 1:
        word1 = sent[i+1][0]
        features.update({
            '+1:word.lower()': word1.lower(),
            '+1:word.istitle()': word1.istitle(),
            '+1:word.isupper()': word1.isupper(),
        })
    else:
        features['EOS'] = True

    return features

def sent2features(sent):
    """Creates a list of feature dictionaries for all words in a sentence."""
    return [word2features(sent, i) for i in range(len(sent))]

def sent2labels(sent):
    """Extracts the list of labels (BIO tags) for a sentence."""
    return [label for token, label in sent]


X = [sent2features(s) for s in train_data + test_data]
y = [sent2labels(s) for s in train_data + test_data]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


crf = sklearn_crfsuite.CRF(
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=True
)

print("CRF model is being trained...")

crf.fit(X_train, y_train)
print("Training completed!")

from sklearn_crfsuite import metrics


y_pred = crf.predict(X_test)


labels = list(crf.classes_)
if 'O' in labels:
    labels.remove('O')


print("-" * 50)
print("CRF Named Entity Recognition (NER) Performance Report:")

print(metrics.flat_classification_report(
    y_test, y_pred, labels=labels, digits=3
))